In [25]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [3]:
data=pd.read_csv(r"C:\Users\dell\Downloads\Iris.csv")

In [4]:
print(data.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa


In [5]:
print("\nDataset Shape:",data.shape)
print("\nDataset Info:\n")
print(data.info())
print("\nChecking Missing Values:\n")
print(data.isnull().sum())


Dataset Shape: (150, 6)

Dataset Info:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB
None

Checking Missing Values:

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64


In [6]:
X=data.iloc[:,:-1]
y=data.iloc[:,-1]
print("\n Feature Data(X):\n",X.head())
print("\n Target Data(y):\n",y.head())


 Feature Data(X):
    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   1            5.1           3.5            1.4           0.2
1   2            4.9           3.0            1.4           0.2
2   3            4.7           3.2            1.3           0.2
3   4            4.6           3.1            1.5           0.2
4   5            5.0           3.6            1.4           0.2

 Target Data(y):
 0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object


In [8]:
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.3,random_state=42
)

print("\nNumber of Training Samples:",len(X_train))
print("Number of Testing Samples:",len(X_test))


Number of Training Samples: 105
Number of Testing Samples: 45


In [14]:
model=GaussianNB()


model.fit(X_train,y_train)
y_pred = model.predict(X_test)

In [15]:
print("\n Model Training Completed Successfully!")
print("\n Actual Values:\n",list(y_test))
print("\nPredicted Values:\n",list(y_pred))


 Model Training Completed Successfully!

 Actual Values:
 ['Iris-versicolor', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa']

Predicted Values:
 [np.str_('Iris-versicolor'), np.str_('Iris-setosa'), np.str_('Iris-virginica'), np.str_('Iris-versicolor'), np.str_('Iris-versicolor'), np.str_('Iris-seto

In [16]:
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix:\n",cm)

Confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


In [21]:
labels = sorted(y_test.unique())
cm_df = pd.DataFrame(cm, index=labels, columns=labels)
print("\nLabeled Confusion Matrix:\n")
print(cm_df)


Labeled Confusion Matrix:

                 Iris-setosa  Iris-versicolor  Iris-virginica
Iris-setosa               19                0               0
Iris-versicolor            0               13               0
Iris-virginica             0                0              13


In [22]:
overall_accuracy=accuracy_score(y_test,y_pred)
print("\nOverall Accuracy:",overall_accuracy)


Overall Accuracy: 1.0


In [23]:
train_acc=model.score(X_train,y_train)
test_acc=model.score(X_test,y_test)

print("\nTraining Accuracy=",train_acc)
print("Testing Accuracy=",test_acc)


Training Accuracy= 0.9904761904761905
Testing Accuracy= 1.0


In [26]:
print("\nClassification Report:\n")
print(classification_report(y_test,y_pred))


Classification Report:

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        19
Iris-versicolor       1.00      1.00      1.00        13
 Iris-virginica       1.00      1.00      1.00        13

       accuracy                           1.00        45
      macro avg       1.00      1.00      1.00        45
   weighted avg       1.00      1.00      1.00        45



In [27]:
print("Calculation of TP, FP, FN, TN for each class:\n")
total=cm.sum()
for i in range(len(cm)):
    TP=cm[i][i]
    FP=cm[:,i].sum()-TP
    FN=cm[i,:].sum()-TP
    TN=total-(TP+FP+FN)
print("For Class",i)
print("TP=",TP)
print("FP=",FP)
print("FN=",FN)
print("TN=",TN)
    
    
    

Calculation of TP, FP, FN, TN for each class:

For Class 2
TP= 13
FP= 0
FN= 0
TN= 32


In [28]:
TP=cm[0][0]
FP=cm[:,0].sum()-TP
FN=cm[0,:].sum()-TP
TN=total-(TP+FP+FN)
print("TP=",TP)
print("FP=",FP)
print("FN=",FN)
print("TN=",TN)

TP= 19
FP= 0
FN= 0
TN= 26


In [30]:
accuracy=(TP+TN)/(TP+TN+FP+FN)
error_rate=1-accuracy
precision=TP/(TP+FP)
recall=TP/(TP+FN)

print("Accuracy:",accuracy)
print("Error Rate:",error_rate)
print("Precision:",precision)
print("Recall",recall)

Accuracy: 1.0
Error Rate: 0.0
Precision: 1.0
Recall 1.0


In [31]:
print(classification_report(y_test,y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        19
Iris-versicolor       1.00      1.00      1.00        13
 Iris-virginica       1.00      1.00      1.00        13

       accuracy                           1.00        45
      macro avg       1.00      1.00      1.00        45
   weighted avg       1.00      1.00      1.00        45



In [32]:
print("\nRESULT:")
print("Naive Bayes classification successfully implemented")
print("Confusion Matrix and performance matrix calculated")


RESULT:
Naive Bayes classification successfully implemented
Confusion Matrix and performance matrix calculated
